apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-all-registries
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-image-registries
    ruleNames:
    - validate-registries
    - autogen-validate-registries
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        - DaemonSet
        - Job
        - CronJob
        - ReplicaSet
        namespaces:
        - teste
        #names:
        #- teste-pod*